### ISSUE TITLE
why I cannot push files to hdfs

### ISSUE THREAD

**Issue by zhangkaikai** [apache/incubator-dolphinscheduler#1217]
When I use the resource center to upload files to HDFS, the background log reports an error cn.escheduler.common.utils.hadoop utils.exists. How should I configure this? Thank you
（在我使用资源中心上传文件到hdfs的时候，后台日志报错   cn.escheduler.common.utils.HadoopUtils.exists，这个应该怎么配置？谢谢）

**Comment by lfyee** [comment]
If the dolphinscheduler is already running, if you want to enable HDFS in the resource center, you need to configure the following files.
(如果dolphinscheduler已经在运行，这时候如果要在资源中心开启HDFS功能，需要如下文件的配置)
conf/common/common.properties
```
# Users who have permission to create directories under the HDFS root path
hdfs.root.user=hdfs
# data base dir, resource file will store to this hadoop hdfs path, self configuration, please make sure the directory exists on hdfs and have read write permissions。"/escheduler" is recommended
data.store2hdfs.basepath=/escheduler
# resource upload startup type : HDFS,S3,NONE
res.upload.startup.type=HDFS
# whether kerberos starts
hadoop.security.authentication.startup.state=false
# java.security.krb5.conf path
java.security.krb5.conf.path=/opt/krb5.conf
# loginUserFromKeytab user
login.user.keytab.username=hdfs-mycluster@ESZ.COM
# loginUserFromKeytab path
login.user.keytab.path=/opt/hdfs.headless.keytab
```
Modify the corresponding parameters according to your own cluster environment. Both api-server and worker-server services need to be configured, modified, and restarted. Since the system is already running, it will not help us create the root and tenant directories, so we need to manually create the root and tenant-related directories.
(根据自己集群环境修改对应的参数，api-server和worker-server两类服务都需要做配置，修改并重启服务，由于系统已经在运行，因此无法帮助我们创建根目录和租户目录，因此我们需要手动创建与根目录和租户相关的目录)
E.g
deploy user: dolphinscheduler
data.store2hdfs.basepath：/escheduler
tenant user：tim
```
# mkdir root
hadoop fs -mkdir  /escheduler
# mkdir tenant
hadoop fs -mkdir -p /escheduler/tim/{resources,udfs}
# change 
hadoop fs -chown -R  dolphinscheduler:dolphinscheduler   /escheduler
```
After the modification, you can use the HDFS function.(修改完后，就可以使用HDFS功能)

**Comment by JunjianS** [comment]
@lfyee ![image](https://user-images.githubusercontent.com/7474234/78957440-e4b8c500-7b17-11ea-9a7f-d20ce284d2ff.png)
这里应该是true把？

**Comment by samz406** [comment]
> @lfyee ![image](https://user-images.githubusercontent.com/7474234/78957440-e4b8c500-7b17-11ea-9a7f-d20ce284d2ff.png)
> 这里应该是true把？

Set to false if authentication is not required, otherwise true
