### ISSUE TITLE
Refactor Alert module

### ISSUE THREAD

**Issue by Technoboy-** [apache/incubator-dolphinscheduler#1694]
Background
  Now, Alert module is a very simple function , just scanning db and triggering alert . As it's a single node, not distributed. 

Suggestion
  As we discuss in the mail list , in this phase , we  will keep this module . So we need to do some refactor about this module.
  1.  Refactor EnterpriseWeChatUtils, using HttpUtils in common instead。
  2.  Using zk lock to keep Alert distributed

**Comment by elonlo** [comment]
My opinion is:

Step 1: define the Manager interface, use JAVA SPI to decouple the sender logic, and support the registration of alarm plugins.

Step 2: let the user call the API instead of scanning the DB regularly to trigger the alarm. Other server depends on the alert module to call the sender api. The specific implementation is to use a separate thread to send asynchronously.

Step 3: get front-end alarm type list through api, and dynamically display alarm types.

Part 4: Split off SMS and enterprise WeChat alert types into plug-ins
