### ISSUE TITLE
Worker group referenced by workflow should not be deleted(被工作流引用的Worker分组应该不能被删除)

### ISSUE THREAD

**Issue by samz406** [apache/incubator-dolphinscheduler#184]
Now if the Worker group referenced by the workflow is deleted, re-modifying the workflow will display the id of the deleted Worker group.
Whether it is possible to increase the judgment here, if the referenced group cannot be deleted.

![image](https://user-images.githubusercontent.com/3055810/56844555-b204c500-68e4-11e9-8197-63007c5ff5eb.png)

---
现在如果工作流引用的Worker分组被删除，重新修改工作流，将显示删除Worker分组的id。
这里是否可以增加判断，如果被引用的分组就不能被删除。

![image](https://user-images.githubusercontent.com/3055810/56844555-b204c500-68e4-11e9-8197-63007c5ff5eb.png)

**Comment by nauu** [comment]
Does this work begin? If not, I can have a try.

**Comment by nauu** [comment]
When workgroup referenced by workflow , And the workflow has instace, The workgroup cannot  be deleted. But if there isn’t any instace in workflow ,the workgroup can be delete , And the page will display value id.

I had pulled request #1398, After the workgroup delete , Use the default workgroup in the page ,Instead of the value id.

**Comment by Yeleights** [comment]
nauu fix it
