### ISSUE TITLE
[Feature] 建议k8s部署的时候默认数据库是MySQL，降低使用门槛

### ISSUE THREAD

**Issue by lookhua** [apache/incubator-dolphinscheduler#2584]
建议k8s部署的时候默认数据库是MySQL，降低使用门槛。
目前随着Tidb等NewSQL数据库的流行，NewSQL会成为技术中台的首选数据库，而Tidb作为一个非常火的项目是搭建技术中台的首选数据库，Tidb兼容MySQL协议而非pg协议，所以incubator-dolphinscheduler的数据直接建在Tidb上是非常合适的

**Comment by liwenhe1993** [comment]
Good idea!
But why not provide both Mysql and PostgreSql?
When user run DolphinScheduler, they can either choice MySql or PostgreSql.

**Comment by chengshiwen** [comment]
@lookhua @liwenhe1993 Because of the commercial license, we cannot directly use the driver and client of MySQL. If you want to use MySQL, you can build a new image based on our `apache/dolphinscheduler` image.

As for MySQL, you need to download [mysql-connector-java-5.1.49.jar](https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.49/mysql-connector-java-5.1.49.jar)

1. Create your `Dockerfile`
```
FROM apache/dolphinscheduler:latest
COPY mysql-connector-java-5.1.49.jar /opt/dolphinscheduler/lib
RUN apk add --update --no-cache mysql-client
```
2. Build the image
```
docker build -f Dockerfile -t apache/dolphinscheduler:mysql .
```

by the way , please update/add title and description in English
