### ISSUE TITLE
[BUG] Upgrade from 1.2.0 to 1.3.0, resource files cannot be found when performing tasks

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2636]
![image](https://user-images.githubusercontent.com/55787491/81380019-b6d99700-913c-11ea-8000-0dd7728c1761.png)

![image](https://user-images.githubusercontent.com/55787491/81380019-b6d99700-913c-11ea-8000-0dd7728c1761.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by lgcareer** [comment]
Hi,I test it by the following steps.
1.Download the 1.2.0 from https://dolphinscheduler.apache.org/zh-cn/docs/release/download.html.
2.Create the resource and process definiiton that used this resource.
3.Execute the process definition in order to it run successful.
4.Checkout the branch dev-1.3.0 and use the same database.
5.Upgrade database and then run the process definition
After the steps,it is also sucdess ful.
