### ISSUE TITLE
Task instance log cannot be updated

### ISSUE THREAD

**Issue by wxg0103** [apache/incubator-dolphinscheduler#2767]
工作流定义完成  运行
工作流实例运行的时候    任务实例的日志没有更新   也没有反应

**Comment by tlhhup** [comment]
Could you paste a screen capture?

**Comment by 597365581** [comment]
can you provide more information？ for example error log

**Comment by xingchun-chen** [comment]
At present, when the shell task is running, you cannot view the log. You can only view the log after the shell task is executed. Does anyone want to fix it?

**Comment by qiaozhanwei** [comment]
flush log has two condition : log size > 64 or flush time interval 1s , otherwise save memory .
if you use sleep test .
for example : 
echo 1111111111
sleep 100
echo 2222222222

echo 1111111111 can read , but doesn't match above conditions . so don't flush
if you doubt why sleep 100 . time condition   doesn't match . because process not output and flush method doesn't execute

**Comment by gabrywu** [comment]
> flush log has two condition : log size > 64 or flush time interval 1s , otherwise save memory .
> if you use sleep test .
> for example :
> echo 1111111111
> sleep 100
> echo 2222222222
> 
> echo 1111111111 can read , but doesn't match above conditions . so don't flush
> if you doubt why sleep 100 . time condition doesn't match . because process not output and flush method doesn't execute

size > 64 ? what's unit of 64? Kib?

**Comment by qiaozhanwei** [comment]
List<String> logBuffer size

**Comment by qiaozhanwei** [comment]
@xingchun-chen have other advice ?

**Comment by gabrywu** [comment]
> At present, when the shell task is running, you cannot view the log. You can only view the log after the shell task is executed. Does anyone want to fix it?

I think this is OK, no need to fix to avoid disk pressure
