### ISSUE TITLE
[BUG] When a user has a resource directory tree, update the user's tenant to report an error

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2860]
![image](https://user-images.githubusercontent.com/55787491/83390197-03ef1700-a424-11ea-8894-674e758cd92d.png)
![image](https://user-images.githubusercontent.com/55787491/83390230-10736f80-a424-11ea-8fd7-c7b9acf27a20.png)

**Which version of Dolphin Scheduler:**
 -[dev_1.3.0]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by 597365581** [comment]
because user's tenant has a resource directory tree  ,so java preject package org.apache.dolphinscheduler.api.service 's UsersService.java code updateUser method 's code:HadoopUtils.getInstance().copy(oldResourcePath + "/" + resource.getName(), newResourcePath, false, true);  will cause this Exception.

**Comment by 597365581** [comment]
I will start to fix it

**Comment by lgcareer** [comment]
@597365581  Hi,I have finished it and tesing now,Could you please choose other issues?Thanks.
