### ISSUE TITLE
[QUESTION] Whether hive can execute multiple SQL statements

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#2953]
Whether hive can execute multiple SQL statements
version: 1.3.0

**Comment by zhuangchong** [comment]
Use ';' to separate

**Comment by BoYiZhang** [comment]
it's not work 

![image](https://user-images.githubusercontent.com/39816903/84473104-0c184380-acbb-11ea-8b71-3280d7327f44.png)

**Comment by gabrywu** [comment]
> Whether hive can execute multiple SQL statements
> version: 1.3.0

Currently ,we can't execute multiple SQL statements. Because the SQL is executed by jdbc Statement object, and each Statement can only run one SQL.
If you want to execute multiple SQL, you'd better merge them into one, which looks like 
`insert into emp(id,name,age) 
select '1','name-1',22 union all 
select '2','name-2',12 union all 
select '3','name-3',18
`
