### ISSUE TITLE
shell脚本ssh root@host 出现主机秘钥验证失败

### ISSUE THREAD

**Issue by One-fengshuai** [apache/incubator-dolphinscheduler#3213]
![image](https://user-images.githubusercontent.com/58324759/87498100-9f151680-c689-11ea-9b5a-a20fa6b27cda.png)

![image](https://user-images.githubusercontent.com/58324759/87498155-b522d700-c689-11ea-9075-1592341b7246.png)
会报错这样的信息。主机用户各种免密已经做了。在liunx上进行操作没有问题。就是在ds上会报错。找不到问题在哪里

**Comment by yangyichao-mango** [comment]
Hi,
You can check the `<<EOF` whether can be executed rightly in linux shell. I run it in my mac, and it produce the same error as yours because of `<<EOF`, you can delete it and try it again.
And please change the title to English.

If you have any question or suggestion, please put forward.

---------
你可以检查下直接在linux上执行这段脚本是否会报错。我mac测试加了 `<<EOF` 和你报一样的错误，可以尝试删除`<<EOF`试下。

**Comment by gabrywu** [comment]
There's nothing to do with dolphinScheduler, you should read the errors deeply

**Comment by One-fengshuai** [comment]
> Hi,
> You can check the `<<EOF` whether can be executed rightly in linux shell. I run it in my mac, and it produce the same error as yours because of `<<EOF`, you can delete it and try it again.
> And please change the title to English.
> 
> If you have any question or suggestion, please put forward.
> 
> 你可以检查下直接在linux上执行这段脚本是否会报错。我本地mac测试加了 `<<EOF` 和你报一样的错误，可以尝试删除`<<EOF`试下。

liunx上执行这段脚本不会报错，我删除了<<EOF测试还是不行

**Comment by One-fengshuai** [comment]
> Hi,
> You can check the `<<EOF` whether can be executed rightly in linux shell. I run it in my mac, and it produce the same error as yours because of `<<EOF`, you can delete it and try it again.
> And please change the title to English.
> 
> If you have any question or suggestion, please put forward.
> 
> 你可以检查下直接在linux上执行这段脚本是否会报错。我本地mac测试加了 `<<EOF` 和你报一样的错误，可以尝试删除`<<EOF`试下。

liunx上测试了 不会报错，删除EOF还是不行
