### ISSUE TITLE
[Question]   Confused about Queue and WorkerGroup  working?

### ISSUE THREAD

**Issue by geosmart** [apache/incubator-dolphinscheduler#3409]
**Describe the question**
foud that source code of sql/dolphinscheduler-postgre.sql has `t_ds_worker_group ` ddl ,
but dolphinscheduler_mysql.sql doesn't have.

confused about `t_ds_queue` and `t_ds_worker_group`.  

when I define a queue and workergroup,how it working?

**Which version of DolphinScheduler:**
 -[1.3.2]

**Additional context**
I know that airflow worker(celery executor) can start with queues to consume command from mq, and task can set queue attribute, 
so task can run in special worker;
and what about ds working for this

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by dailidong** [comment]
t_ ds_ queue is used to correspond to hadoop yarn queue,  The queue in DolphinScheduelr refers to which queue of yarn is used by the tenant, the tenant is binding the queue on the yarn. By the way, you should create queue on yarn first when you want to use 

1.3.2 didn't use t_ds_worker_group table any more, because worker set worker group in worker.properties, use worker  group table  couldn't support k8s, because worker ip always change on k8s
