### ISSUE TITLE
[Bug][API] OOM occurs when uploading large files

### ISSUE THREAD

**Issue by yy0812** [apache/incubator-dolphinscheduler#3643]
**Describe the bug**
When uploading large files(353MB) in the resource center, the page progress bar is stuck at 100%, view the background API logs and find OOM
![image](https://user-images.githubusercontent.com/32183971/91937354-4c201d00-ed24-11ea-9130-faa9f071c30c.png)
I fixed this after modifying the JVM parameters in the` /bin/dolphinscheduler-daemon.sh` script, but felt it was not a good idea to do so.Do you want to add a configuration item or an FAQ?
![image](https://user-images.githubusercontent.com/32183971/91937600-d6688100-ed24-11ea-97de-16683ca8778a.png)

**Which version of Dolphin Scheduler:**
 -[1.3.2-release]

**Comment by yangyichao-mango** [comment]
This actually is not a bug， If you

**Comment by CalvinKirs** [comment]
> This actually is not a bug， I think we can Add it to FAQ, if you are interested in putting your solution to FAQ, please leave a message.

+1

**Comment by yy0812** [comment]
> This actually is not a bug， I think we can Add it to FAQ, if you are interested in putting your solution to FAQ, please leave a message.

I can help to improve FAQ, but I don't know how to submit

**Comment by Baoqi** [comment]
I think we may be able to do better for this.  for multipart files in springboot & jetty, it should use streaming mode to not directly load the whole file in memory. 

But according to spring boot's documentation:  https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/web/servlet/MultipartProperties.html

       `file-size-threshold specifies the size threshold after which files will be written to disk. The default is 0.`
        
The default is 0, so, it will parse uploaded multipart file into memory, instead of writing to temp file.

So, I guess set the   `spring.http.multipart.file-size-threshold`   to a value like  10MB.  may avoid the OutOfMemory error


spring.http.multipart.file-size-threshold=10MB


 Can you try whether this will reduce memory usage?

**Comment by yangyichao-mango** [comment]
I think If we can implement it with streaming mode, it will be better. You can try it as baoqi way.


------------------ Original ------------------
