### ISSUE TITLE
[Question] globalParams duplicated in table[t_ds_process_definition]

### ISSUE THREAD

**Issue by geosmart** [apache/incubator-dolphinscheduler#3653]
**Describe the question**

I found that table t_ds_process_definition has persist duplicate  global_params,
column   `process_definition_json` 's globalParams field value  is duplicate with the `global_params` column value

---

is some legacy vesion make this duplicate?

**Which version of DolphinScheduler:**
 -[1.3.2-preview]

**Comment by xingchun-chen** [comment]
Thank you for your feedback. 
Since these two fields are both useful, the front and back ends have changed a lot. 
The next version is going to disassemble fast json, this field will be changed, so the issue will be closed, and you can follow the email dev@dolphinscheduler.apache.org for specific progress
