### ISSUE TITLE
[Bug][docker] Unable to upload udf files when accessing port 8888 through nginx

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#3795]
1.accessing port 8888 in web page
2.upload file in UDF manage page, that unable to upload  file successfully

![image](https://user-images.githubusercontent.com/55787491/93984307-36979380-fdb6-11ea-8d20-f5e87ba91214.png)

**Which version of Dolphin Scheduler:**
 -[1.3.2-release]

**Comment by dailidong** [comment]
any update?

**Comment by CalvinKirs** [comment]
hi, I would love to check this question, can you provide more detailed information?

**Comment by dailidong** [comment]
> any update?

it is because the nginx upload size limited , when you upload a bigger file, this error will be shown, you have two options to choose:
1、 change the nginx conifg and add upload size , you can referer this article: https://blog.csdn.net/aa390481978/article/details/103782790

2、don't visit the UI through 8888, you can visit UI : http://{api server ip}:12345/dolphinscheduler/ui/view/login/index.html, then upload the large file
