### ISSUE TITLE
[Bug]use dolphinscheduler1.3.1 scheduler flink1.11 - Could not build the program from JAR file: JAR file does not exist: -yn

### ISSUE THREAD

**Issue by lishiyucn** [apache/incubator-dolphinscheduler#3987]
dolphinscheduler1.3.1

flink1.11

use dolphinscheduler1.3.1 scheduler flink1.11 
the log error is : -yn 
Could not build the program from JAR file: JAR file does not exist: -yn

Use the help option (-h or --help) to get help on the command.

the flink1.10 remove the -yn and -yST parameters

Which dolphinscheduler version  will support the flink1.11??

**Comment by chengshiwen** [comment]
@lishiyucn The latest dev branch has supported flink version selection as follow.

Maybe if 1.3.4-release cherry-pick the related commits in dev branch, so that 1.3.4-release will support the flink1.11.

`-yst` has removed from flink 1.10, so just don't specify this option in `other args`.

[#4166] also fixed `--qu` problem.

![image](http://g.recordit.co/gFwAZi7U09.gif)

**Comment by lgcareer** [comment]
@chengshiwen  Hi,Whether you can submit a pr on 1.3.4-release?
