### ISSUE TITLE
[Question] When a single node has been installed, I want to install workers on other nodes. How do I separate them?

### ISSUE THREAD

**Issue by zhmingyong** [apache/incubator-dolphinscheduler#4075]
When a single node has been installed, I want to install workers on other nodes. How do I separate them?

在已经安装好单节点的情况下，我想把worker安装到其它节点上，要如何分离出来呢？

**Comment by zhuangchong** [comment]
It is suggested to install the official documents and rebuild the cluster environment, in which the database part can be not operated, and the database data used in the stand-alone version can be used. Because you need to sort out the configuration properties of the configuration file to consider decoupling, it's not as fast as reconstructing it from the official site.

---
个人建议安装官方文档，重新搭建集群环境，其中数据库部分可以不操作，使用单机版使用的数据库数据。因为考虑分离的化你需要整理配置文件的配置属性，还不如按照官网重新搭建来的快。
https://dolphinscheduler.apache.org/zh-cn/docs/1.3.3/user_doc/cluster-deployment.html

**Comment by xingchun-chen** [comment]
whether your problem has solved?

**Comment by chengshiwen** [comment]
Close the question since it has been replied
