### ISSUE TITLE
[Bug][Worker] All worker nodes can receive the kill task message

### ISSUE THREAD

**Issue by home123wx** [apache/incubator-dolphinscheduler#4079]
**Describe the bug**

When the workflow instance is stopped, all workers can receive the kill task message, which will lead to the node that does not run the task and kill the process with the same PID on the worker node.
(当停止工作流实例时，所有的worker都能接受到kill task的消息，会导致没有运行该任务的Worker节点，误杀掉该节点上相同pid的进程)

**To Reproduce**
Steps to reproduce the behavior, for example:
1. run a process definition （运行一个工作流，可创建一个shell task执行sleep命令）
2. stop this process instance （停止对应的工作流定义）
3. you can see the kill task message in all worker logs（日志中可以看到所有的worker都有收到kill task的消息）

**Expected behavior**

Only the worker of run task receives the message （在所有的worker日志中都能看到kill task的消息）

**Which version of Dolphin Scheduler:**
 -[1.2.0]

**Comment by zhuangchong** [comment]
This problem should have been fixed in the 1.3.x branch, and the communication between master and worker should be changed to netty communication. You can look at the host specified in the MasterTaskExecThread class in the source code to communicate with worker, so when stopping a task, you can specify the worker where the task is to kill the task.

---
这个问题应该在1.3.x分支已经修复，master 和worker 通信改成netty通信，可以看一下源码MasterTaskExecThread 类里面已经指定任务所在的host 进行和worker通信，所以在停止任务时，可以指定任务所在的worker去kill任务.

**Comment by CalvinKirs** [comment]
already fixed in 1.3.x
