### ISSUE TITLE
安装脚本的bug

### ISSUE THREAD

**Issue by wukefang** [apache/incubator-dolphinscheduler#4082]
版本：1.3.3
执行 sh install.sh 后   会自动修改 datasource.properties文件的内容：
执行前：
spring.datasource.password=&sbflsdhjfapsfl
执行后：
spring.datasource.password=spring.datasource.password=&sbflsdhjfapsflsbflsdhjfapsfl
描述：
不知道是否和密码中第一个字符是&有关，执行后会把spring.datasource.password=&sbflsdhjfapsfl 复制一边 并去掉&字符
导致ui登陆失败

**Comment by lenboo** [comment]
Official English， please change the title and content to english, thx.

**Comment by lenboo** [comment]
@wukefang

**Comment by zhuangchong** [comment]
Because of the special characters & lead to, you can in the conf/datasource. The properties file manually modify the password attribute value or perform before:

spring.datasource.password=\&sbflsdhjfapsfl

As for the handling of password containing special characters, we will think about how to deal with this problem. If you have good ideas, please leave a message

---
是因为特殊字符&导致的，你可以在conf/datasource.properties文件内手动修改password属性值或执行前：
spring.datasource.password=\&sbflsdhjfapsfl

关于密码含有特殊字符的处理，我们会想一下要如何处理规避这个问题，如果您有好的想法，欢迎留言

**Comment by zhuangchong** [comment]
![image](https://user-images.githubusercontent.com/37063904/99662252-f72cb100-2a9f-11eb-9144-5ac32a052dff.png)

**Comment by wukefang** [comment]
Thank you！ @zhuangchong @lenboo 
that notice is very good, it will not waste a long time on finding the reason;
