### ISSUE TITLE
After the system hangs up, the master worker registration information of the zk cache or mysql storage will cause the restart to fail.（系统挂机后，zk缓存或mysql存储的master worker注册信息会导致重启失败）

### ISSUE THREAD

**Issue by pxfman** [apache/incubator-dolphinscheduler#565]
As the title, the system restarts using start_all.sh will report, the master already registted.

---
如题，系统重启使用start_all.sh会报，master already registted。

**Comment by boandai** [comment]
1.1.0 version will fix it , thx !

**Comment by qiaozhanwei** [comment]
This is not a bug. After the master or worker is dropped, the zk temporary node will still exist (this is the internal mechanism of zk), and if there is a prompt message. To solve the problem in two ways, either manually delete the zk temporary node information, and then start it, or wait until the zk temporary node is deleted before starting. We can't delete the temporary node at startup because the running node may be deleted by mistake.

这不是一个bug，master或者worker掉后，zk临时节点还是会存在（这是zk内部机制），这时如果启动会有提示信息。两种方式解决，要么先手动删除zk临时节点信息，然后启动，或者等到zk临时节点删除之后再启动。我们不能在启动的时候删除临时节点，因为可能会误删除正在运行的节点

**Comment by lvqiushi** [comment]
> This is not a bug. After the master or worker is dropped, the zk temporary node will still exist (this is the internal mechanism of zk), and if there is a prompt message. To solve the problem in two ways, either manually delete the zk temporary node information, and then start it, or wait until the zk temporary node is deleted before starting. We can't delete the temporary node at startup because the running node may be deleted by mistake.
> 
> 这不是一个bug，master或者worker掉后，zk临时节点还是会存在（这是zk内部机制），这时如果启动会有提示信息。两种方式解决，要么先手动删除zk临时节点信息，然后启动，或者等到zk临时节点删除之后再启动。我们不能在启动的时候删除临时节点，因为可能会误删除正在运行的节点



> This is not a bug. After the master or worker is dropped, the zk temporary node will still exist (this is the internal mechanism of zk), and if there is a prompt message. To solve the problem in two ways, either manually delete the zk temporary node information, and then start it, or wait until the zk temporary node is deleted before starting. We can't delete the temporary node at startup because the running node may be deleted by mistake.
> 
> 这不是一个bug，master或者worker掉后，zk临时节点还是会存在（这是zk内部机制），这时如果启动会有提示信息。两种方式解决，要么先手动删除zk临时节点信息，然后启动，或者等到zk临时节点删除之后再启动。我们不能在启动的时候删除临时节点，因为可能会误删除正在运行的节点

master或者worker可以通过监听Disconnected 事件并注册回调方法删除masterZnode临时节点，一个建议。

**Comment by CalvinKirs** [comment]
done
