### ISSUE TITLE
[Feature] About if DS should own sudo permissions

### ISSUE THREAD

**Issue by buildupchao** [apache/incubator-dolphinscheduler#868]
Hello, I want to ask you about the sudo permissions related to DolphinScheduler. There is a risk that causes the HDFS data of other departments or users to be deleted if somebody enters some wrong commands. Besides, We cannot control over the user's operating behavior to avoid terrible things. For this, DS team has any plan to resolve this question?

**Comment by gaojun2048** [comment]
Hi,@buildupchao 
Maybe you know, DolphinScheduler need start with a user that have sudo permissions. Because DolphinScheduler is support multi-tenant . In DolphinScheduler every task need be run as the tenant . So ,  DolphinScheduler need use 'sudo su - {tenant} -c ' to run the task script . 

For those users who are unable to obtain sudo privileges due to company security reasons, we recommend that you apply for a user with sudo privileges. After deployment, the password is given by Operator K.

**Comment by buildupchao** [comment]
> Hi,@buildupchao
> Maybe you know, DolphinScheduler need start with a user that have sudo permissions. Because DolphinScheduler is support multi-tenant . In DolphinScheduler every task need be run as the tenant . So , DolphinScheduler need use 'sudo su - {tenant} -c ' to run the task script .
> 
> For those users who are unable to obtain sudo privileges due to company security reasons, we recommend that you apply for a user with sudo privileges. After deployment, the password is given by Operator K.

Ok. Thanks for you help!
