### ISSUE TITLE
[Feature]A lack of Privilege Management Module(缺乏有权限管理系统)

### ISSUE THREAD

**Issue by liehuoqiangni** [apache/incubator-dolphinscheduler#879]
1.At present, users can only manage and view the process they created by themselves.(目前用户只能自己管理，查看自己创建的process)。
2.Is it considered that users in the same group can co-manage the process created by the people in the group?(是否考虑让同组的用户，可以共同管理组内人员创建的process？)
For example, by adding the privilege management module to achieve this goal.(比如通过加入权限管理模块，来实现此功能。)

**Comment by dailidong** [comment]
good idea！

please update/add title and description for global communication! thx!

**Comment by BruceQiu90** [comment]
I have two idea.
1. User who created the DAG is the DAG's admin, he can grant privilege to other people.
2. Create a group, every group has three different roles, there are admin, developer, visitor. Admin can perform any operation, developer can only execute, view the DAG content, visitor can only view the DAG content.
If you agree with my idea, I would like to work on this.

**Comment by dailidong** [comment]
how about user <--> role <--> permissions architecture design ? like some other systems, they usually use this design to implement permission controll !  system admin will have super permission, and he can set or add role, and can set this role have the permissions!  

the all permissions will be  ready when system deployed!
 

this issue is very open , anybody who interesting in can give ideas

**Comment by CalvinKirs** [comment]
please see #1333 
Focus on #1333 discussion
